/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : qrencode
 #	author : miyako
 #	2016/02/08
 #
 # --------------------------------------------------------------------------------*/



// --- qrencode
void QRCODE(sLONG_PTR *pResult, PackagePtr pParams);
void QRCODE_ARRAY(sLONG_PTR *pResult, PackagePtr pParams);

enum output_type_t {
    QR_OUTPUT_PNG,
    QR_OUTPUT_SVG
};

#include "qrencode.h"
#include "png.h"

#define INCHES_PER_METER (100.0/2.54)

#define QR_Mode_Unicode 0x0000
#define QR_Mode_Kanji   0x0001
#define QR_Mode_Micro   0x0002

void toSVG(QRcode *qr, int margin, int size, int dpi, C_TEXT &_dump, sLONG_PTR *pResult);
void toPNG(QRcode *qr, int margin, int size, int dpi, C_TEXT &_dump, sLONG_PTR *pResult);

void toSVGs(QRcode *qr, int margin, int size, int dpi, int pos, PA_Variable *param);
void toPNGs(QRcode *qr, int margin, int size, int dpi, int pos, PA_Variable *param);

void write_data_fn(png_structp png_ptr, png_bytep buf, png_size_t size);
void output_flush_fn(png_structp png_ptr);
